# Generated by Django 6.0.2 on 2026-02-11 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('CONFIRMADO', 'CONFIRMADO'), ('SEPARADO', 'SEPARADO'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('CANCELADO', 'CANCELADO')], db_index=True, default='PENDENTE', max_length=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observations', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('CONFIRMADO', 'CONFIRMADO'), ('SEPARADO', 'SEPARADO'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('CANCELADO', 'CANCELADO')], max_length=16)),
                ('to_status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('CONFIRMADO', 'CONFIRMADO'), ('SEPARADO', 'SEPARADO'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('CANCELADO', 'CANCELADO')], max_length=16)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='orders_custome_18fe5d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer', 'idempotency_key'), name='uq_order_customer_idempotency'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_items_product_a53db1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'changed_at'], name='order_statu_order_i_623f54_idx'),
        ),
    ]
