# Generated by Django 5.1.6 on 2026-02-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDomainEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_domain_events",
            },
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="order_items_order_i_26ad88_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="order_items_product_a53db1_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderstatushistory",
            name="order_statu_order_i_623f54_idx",
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderdomainevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_events",
                to="orders.order",
            ),
        ),
    ]
