# Generated by Django 5.1.6 on 2026-02-11 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderdomainevent_and_more"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="order_items_order_i_26ad88_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="order_items_product_a53db1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["order", "changed_at"], name="order_statu_order_i_623f54_idx"
            ),
        ),
    ]
